### PR TITLE
build.sh: huge refactoring (matching upstream {Black}Arch).

### PR DESCRIPTION
**Pull request by PedroSFreitas**
**This Pull Request tries to get MantOS updated with the latest building process from Arch Linux** and BlackArch. Also reading the README I could notice that the project was based as well on ArchBang, a distribution based on Arch Linux, but now deprecated; which I chose to remove from MantOS.
I believe using AUR packages out of the blue could be dangerous, so I removed it too; all packages now come from official repositories (Arch or BlackArch).

**This PR will address:**

- new .gitignore file
- a little merging with branch master (readme)
- README is now, where possible, limited to 80 char column for easy reading
- README is now clear about Arch Linux and BlackArch dependencies and more (root, etc)
- a TODO file was added for directions of the project (it should be reviewed however)
- a huge refactoring/deleting of unnecessary and/or out of date files (including configuration files): _this can sound strange, but I think the best approach is usually to remove and add when needed_
- adding new shell as default (zsh with grml configuration package - a boost in production)
- new lxdm.conf configuration file
- added motd file
- added radare2, cutter and gdb configuration file
- added XFCE + goodies as the Desktop Environment: It's still lightweight enough and covers all user needs
- the customize script was refactored, added comments and made it clear enough for future updates
- added/edited: hosts, hostname, issue and locale.conf
- the boot loader is now complete and matching with upstream (Arch Linux)
- font configuration was added to make it clear and readable (easy on the eyes)
- network is enabled by default (dangerous? We don't do that in BlackArch).
- credentials: root:mantos

I think it was really important to make this cleanup and start from the ground up matching with upstream. The ISO has now 2.1GB, it boots really fast (tested on VirtualBox and on a real pc using legacy boot). The choice of XFCE simplify our work and make it easier for customization.

Note: this work was done only for the sake of creating a base for future work (when I have the requirements). That said, it probably won't match with what Lifars has in mind by now.

Note2: workflow suggested: pushing to branch dev, once tested and approved by Lifars, merged into master and a new ISO released.

Next steps (I think/suggest):

1. new color scheme for the terminal (maybe matching Lifars colors?)
2. new color theme for XFCE (maybe matching Lifars colors?)
3. new lxdm theme/background (maybe matching Lifars colors?)
4. check field needs: a test by someone experienced on forensics will definitely improve it
5. packages selection review: all the tools needed are installed? Maybe remove a few or add others?

### CODE REVIEW

**Comment by PedroSFreitas** [comment]
@mpiletskaya 
a link for the ISO: https://mega.nz/#!Gww3nRBI!wzmiUVQYvoKdak6Y88A8iBhxDLztE2mB5tRIReX9vLI
I suggest running it on a virtualbox. Just a note: the cowspace is 65% of the actual RAM, so 1,5 to 2 GB of RAM would be more than enough for a test.
the sha1sum of it is:
```
cd57ad028d5085e42a5dc39f29444025451d54a0  mantos-2018.03.08-x86_64.iso
```

**Comment by mbStavola** [comment]
WRT the networking comment-- its been over two years at this point, but IIRC we had originally had it so you started in promiscuous mode because this was meant to be deployed in an environment where we'd be actively capturing network data on prem.

Not saying it was the correct thing to do or something you should even consider, but that's just the historical context.

**Comment by eugf** [comment]
Arch Bang was deprecated? That explains why everything broke all of a sudden. Their wiki says Jan 2017 was the last preview... yeah that was around when it broke. Thanks for your interest in rebuilding this @PedroSFreitas ! Your optimizations sound great. To add onto what @mbStavola said, it was originally intended to do promiscuous mode. Our test machine was able to do it without the need for buying external antennas, like Alfa.

**Comment by PedroSFreitas** [comment]
> because this was meant to be deployed in an environment where we'd be actively capturing network data on prem.

@mbStavola : That makes sense, thanks for clarifying.

> Not saying it was the correct thing to do or something you should even consider, but that's just the historical context.

> To add onto what mbStavola said, it was originally intended to do promiscuous mode. Our test machine was able to do it without the need for buying external antennas, like Alfa.

@mbStavola , @eugf : I think it's really interesting. That hasn't crossed my mind. :thinking: 

> Your optimizations sound great.

@eugf : Thanks, but they are actually really simple. XFCE makes everything easier on the user side and the whole change was more to get it up and running (new Arch Linux & BlackArch building process). The rest was easy because I did back in BA (configuration, customize.sh, etc).

**Pull request merged**
